name : Foundation5/github pages/Jykill starter
brand : A
description : This is the description of my site
keyword : 
url : /
email : amart1892@gmail.com
twitter : alx_mrtnz
github : alxmrtnz
author : Alex Martinez
analytics : UA-8418273-8
year : 2015
markdown : kramdown
exclude :
  - node_modules
